GET https://3d3fs4f166:ztpejeu8qo@alguien-sabe-7413340520.us-west-2.bonsaisearch.net:443


###
PUT https://3d3fs4f166:ztpejeu8qo@alguien-sabe-7413340520.us-west-2.bonsaisearch.net:443/comentario
content-type: application/json

{
    "mappings": {
        "properties": {
            "tipo": {
                "type": "integer"
            },
            "creador": {
                "type": "keyword"
            },
            "texto": {
                "type": "text"
            },
            "bloqueado": {
                "type": "boolean"
            },
            "borrado": {
                "type": "boolean"
            },
            "detalles": {
                "type": "object"
            }
        }
    }
}

###
GET https://3d3fs4f166:ztpejeu8qo@alguien-sabe-7413340520.us-west-2.bonsaisearch.net:443/comentario/_mapping

###
DELETE https://3d3fs4f166:ztpejeu8qo@alguien-sabe-7413340520.us-west-2.bonsaisearch.net:443/comentario

###
POST https://3d3fs4f166:ztpejeu8qo@alguien-sabe-7413340520.us-west-2.bonsaisearch.net:443/comentario/_doc HTTP/1.1
content-type: application/json

{
    "tipo": 1,
    "creador": "2",
    "texto": "se esta ",
    "bloqueado": false,
    "borrado": false,
    "detalle": {
        "categoria": "Pruebas",
        "padre": "nhneothnothntohunth"
    }
}

###
GET https://3d3fs4f166:ztpejeu8qo@alguien-sabe-7413340520.us-west-2.bonsaisearch.net:443/comentario/_search
content-type: application/json

{
    "query" : {
        "match_all" : {}
    }
}