GET http://localhost:9200

###
GET http://localhost:9200/


###
PUT http://localhost:9200/comentario
content-type: application/json

{
	"settings": {
		"analysis": {
			"filter": {
				"autocomplete_filter": {
					"type": "edge_ngram",
					"min_gram": 1,
					"max_gram": 20
				}
			},
			"analyzer": {
				"autocomplete": {
					"type": "custom",
					"tokenizer": "standard",
					"filter": [
						"lowercase",
						"autocomplete_filter"
					]
				}
			}
		}
	},
	"mappings": {
		"properties": {
			"autor": {
				"properties": {
					"id": {
						"type": "integer"
					},
					"usuario": {
						"type": "keyword"
					}
				}
			},
			"padre": {
				"type": "keyword"
			},
			"texto": {
				"type": "text",
				"analyzer": "autocomplete",
				"search_analyzer": "standard"
			},
			"fechaCreacion": {
				"type": "date"
			},
			"bloqueado": {
				"type": "boolean"
			},
			"borrado": {
				"type": "boolean"
			},
			"detalles": {
				"type": "object"
			}
		}
	}
}

###
GET http://localhost:9200/comentario/_mapping

###
DELETE http://localhost:9200/comentario

### Comentario
POST http://localhost:9200/comentario/_doc HTTP/1.1
content-type: application/json

{
	"autor": {
		"id": 11,
		"usuario": "ezequiel"
	},
	"padre": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9",
	"texto": "Este es mi primer comentario",
	"borrado": false,
	"detalle": {
		"categoria": "comentarios"
	}
}

### Pregunta
POST http://localhost:9200/comentario/_doc HTTP/1.1
content-type: application/json

{
	"autor": {
		"id": 11,
		"usuario": "ezequiel"
	},
	"texto": "Este es mi cuarto comentario",
	"borrado": false,
	"detalle": {
		"categoria": "comentarios"
	}
}

###
GET http://localhost:9200/comentario/_search
content-type: application/json

{
    "query" : {
        "match_all" : {}
    }
}