GET http://localhost:3000/comentario
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7InVzdWFyaW9faWQiOjExLCJpcCI6IjE3Mi4yMS4wLjIiLCJ1c3VhcmlvIjoiZXplcXVpZWwifSwiZXhwIjoxNTk2MjgzMDg2LCJpYXQiOjE1OTYxOTY2ODZ9.cGJj93U_36MCg08W7yKOX8JPOWpCL7FKOwZQM5pp3SU

###
GET http://localhost:3000/comentario?q=prim
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7InVzdWFyaW9faWQiOjExLCJpcCI6IjE3Mi4yMi4wLjUiLCJ1c3VhcmlvIjoiZXplcXVpZWwifSwiZXhwIjoxNTk3Njg1MjM4LCJpYXQiOjE1OTc1OTg4Mzh9.Z8-SFR2AUDSpUpt_9fL4FQExI9YDS9hUQuuNVlIbnvk

###
GET http://localhost:3000/comentario/A4mlfnMB-Ts7nksNIsXs/comentarios
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7InVzdWFyaW9faWQiOjExLCJpcCI6IjE3Mi4yMi4wLjUiLCJ1c3VhcmlvIjoiZXplcXVpZWwifSwiZXhwIjoxNTk3Njg1MjM4LCJpYXQiOjE1OTc1OTg4Mzh9.Z8-SFR2AUDSpUpt_9fL4FQExI9YDS9hUQuuNVlIbnvk


###
GET http://localhost:3000/comentario/A4mlfnMB-Ts7nksNIsXs
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7InVzdWFyaW9faWQiOjExLCJpcCI6IjE3Mi4yMi4wLjUiLCJ1c3VhcmlvIjoiZXplcXVpZWwifSwiZXhwIjoxNTk3Njg1MjM4LCJpYXQiOjE1OTc1OTg4Mzh9.Z8-SFR2AUDSpUpt_9fL4FQExI9YDS9hUQuuNVlIbnvk


### Pregunta
POST http://localhost:3000/comentario
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7InVzdWFyaW9faWQiOjExLCJpcCI6IjE3Mi4yMi4wLjUiLCJ1c3VhcmlvIjoiZXplcXVpZWwifSwiZXhwIjoxNTk3Njg1MjM4LCJpYXQiOjE1OTc1OTg4Mzh9.Z8-SFR2AUDSpUpt_9fL4FQExI9YDS9hUQuuNVlIbnvk
content-type: application/json

{
	"autor": {
		"id": 11,
		"usuario": "ezequiel"
	},
	"texto": "Esta es mi primera pregunta",
	"borrado": false,
	"detalle": {
		"categoria": "comentarios"
	}
}


### Respuesta
POST http://localhost:3000/comentario
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7InVzdWFyaW9faWQiOjExLCJpcCI6IjE3Mi4yMi4wLjUiLCJ1c3VhcmlvIjoiZXplcXVpZWwifSwiZXhwIjoxNTk3Njg1MjM4LCJpYXQiOjE1OTc1OTg4Mzh9.Z8-SFR2AUDSpUpt_9fL4FQExI9YDS9hUQuuNVlIbnvk
content-type: application/json

{
	"autor": {
		"id": 11,
		"usuario": "ezequiel"
	},
    "padre": "MDRg-HMBQjYKbkVT7Enw",
	"texto": "Esta es mi segunda respuesta",
	"borrado": false,
	"detalle": {
		"categoria": "comentarios"
	}
}


###
GET http://localhost:3000/comentario
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7InVzdWFyaW9faWQiOjExLCJpcCI6IjE3Mi4yMi4wLjUiLCJ1c3VhcmlvIjoiZXplcXVpZWwifSwiZXhwIjoxNTk3Njg1MjM4LCJpYXQiOjE1OTc1OTg4Mzh9.Z8-SFR2AUDSpUpt_9fL4FQExI9YDS9hUQuuNVlIbnvk

